chore: improve issue templates
qinhua/halo-theme-joe2.0 pull request #55
Opened 2021-12-12 10:05 UTC by ruibaby

提供 issue 提交表单 UI。

示例：

1. 缺陷报告：https://github.com/ruibaby/halo-theme-joe2.0/issues/new?assignees=&labels=bug&template=bug_report.yml
2. 功能建议：https://github.com/ruibaby/halo-theme-joe2.0/issues/new?assignees=&labels=enhancement&template=feature_request.yml

2021-12-12 10:08 UTC, JohnNiang requested changes

2021-12-12 10:08 UTC, JohnNiang commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
New line needed.

2021-12-12 10:08 UTC, JohnNiang commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
New line needed.

2021-12-14 07:28 UTC, merged

2021-12-14 07:29 UTC, qinhua commented
感谢大佬的贡献👍